### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot-metrics#2]

**Comment by pdehaan** [comment]
Bare minimum is probably:

```yaml
env:
  browser: true
  es6: true
  mocha: true
  node: true
  webextensions: true

extends:
  - eslint:recommended

globals:
  BroadcastChannel: false
  Components: false
  Services: false

rules:
  eqeqeq: error
  no-console: warn
  quotes: [error, single]
```

Gives me about 28 errors and 3 warnings. If I run `eslint . --fix` and autofix any easy errors, that number drops down to 20 errors and 3 warnings.
